name:                nixys-server-box
version:             0.2.0
github:              "nick-chandoke/nixys-server-box"
license:             BSD3
author:              "Nicholas Chandoke"
maintainer:          "nicholas.chandoke@gmail.com"
copyright:           "2018-2019 Nicholas Chandoke"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- aws >= 0.21.1
- bytestring
- bytestring-trie
- conduit
- conduit-extra
- containers
- fast-logger
- filepath
- http-client
- http-client-tls
- http-conduit
- http-types
- network
- resourcet
- rio
- streaming-commons
- text
- typed-process
- vault
- wai
- wai-extra
- warp
- warp-tls
- zlib

library:
  source-dirs: src

default-extensions:
- ApplicativeDo
- Arrows
- BangPatterns
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- NumDecimals
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- UndecidableInstances
- ViewPatterns

tests:
  nixys-server-box-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nixys-server-box
